app.environment=prod

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

logging.level.com.example.chokokane=INFO

app.cookie.secure=true
app.cookie.same-site=Lax