app.environment=local

spring.config.import=optional:classpath:application-local-secret.properties

spring.datasource.url=jdbc:mysql://localhost:3306/expense_manager
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.com.example.chokokane=DEBUG